cujojs/most

lib/combinator/timeslice.js
test/timeslice-test.js

This splits Bound into MinBound and MaxBound, simplifies both, and simplifies WithinSink as well.
Still needs:
Fix #108

Fix timeslice end signal issues

---

docs/api.md
lib/combinator/transduce.js
most.js
package.json
test/combinator/transduce-test.js

Add `transduce` API for using composed transducers with most.js streams.
Still needs:
See #90

Add transduce

---

docs/recipes/README.md
docs/recipes/event-delegation.md
docs/recipes/unfold-promises.md

@briancavalier Sorry for the delay finally got my computer back.. i've included two recipes as 1st pass at it please let me know your thoughts or if I am way off, etc :smile:

1st pass at recipes

---

docs/api.md
lib/source/fromEvent.js
lib/source/iterate.js
most.js
test/most-test.js
test/source/MulticastSource-test.js
test/source/fromEvent-test.js
test/source/iterate-test.js

Remove pre-1.0.0 deprecations

---

docs/api.md
docs/concepts.md
most.js

Remove experimental designation for during()

---

lib/source/create.js
test/source/create-test.js

Includes unit test derived from http://requirebin.com/?gist=fcabd52e0c21abfa10bc
Close #129

Forcibly prevent events after end to account for misbehaving producers

---

README.md

Extract some info from #96 and integrate into README.
Close #99

Update README with info from #96

---

docs/api.md

Fix since docs

---

lib/base.js
lib/source/from.js
test/source/from-test.js

now we can do `most.from(arguments)` or `most.from(nodeList)`, etc

added support for arrayLike items

---

docs/api.md

Removed `lift` from TOC and added `flatMapEnd`
@briancavalier I don't know if `flatMapEnd` ascii diagram or description is ideal but I just wanted to get the ball rolling.

doc updates

---

lib/scheduler/Scheduler.js

Fix subtle bug in scheduler task cancelation.
Fix #197

Fix scheduler task cancelation bug

---

most.js
test/most-test.js

Fix multicast

---

test/switch-test.js

Some tests still haven't ported to use virtual time.  This PR ports the `switch` tests to use virtual time, which isn't subject to any JS timer quirks or platform timer differences.

Use virtual timers for switch tests

---

docs/api.md

Add information about handling events with more than one argument.

Update fromEvent documentation

---

README.md

Add ascii logo

---

package.json

Update to `@most/multicast` 1.1.1 for dispose fix.
Fix #247

Update to @most/multicast 1.1.1

---

lib/fusion/Map.js

I can't find a situation where it actually improves performance, and have found a few where it hurts.  More testing is definitely needed, but opening this now so I'm motivated to do it :)

Remove coallescing filtermap+map fusion

---

package.json

It's been out for a few months now, and seems like a transparent update so far.  Would be good to update if it's seamless.

Update to buster 0.8.0

---

package.json

Update markdown-doctest to 0.4.0

---

package.json

Oops, we missed this in #186.  Once this is merged, we can release 0.19.6
cc @TylorS @AlexGalays

Add type-definitions to package.json files

---

docs/api.md

Suggestion from https://github.com/cujojs/most/pull/278#issuecomment-223829955

Add example of zipping stream with periodic to emit in intervals

---

lib/source/periodic.js

Plus minor cleanup. Close #251

Stop multicasting periodic by default

---

lib/source/fromEvent.js

Stop multicasting fromEvent

---

src/index.js
test/most-test.js

Adds from static method to the constructor for ES Observable compatibility

feat(Stream): add static from method to Stream

---

bower.json
package.json

Add missing `src/` dir and `module` field for future compat.
See #301

fix(package): add src dir and module to package.json files

---

LICENSE

chore(license): Add license file

---

type-definitions/most.d.ts

Added combineArray overloads for arbitrary lengths.

---

docs/api.md

fix https://github.com/cujojs/most/issues/335

fix type in mergeConcurrently doc

---

README.md

It is useful, when i am using it in something like JSBin, which i use a lot to give quick demos/tutorials .

cnd via unpkg

---

test/perf/README.md

Followon to #372 to add perf results that include xstream.
cc @staltz

Add xstream perf results

---

docs/api.md

Add note about from throwing TypeError synchronously

---

src/source/fromIterable.js

fromIterable was quite old code, from a time when we believed that it was more important to provide concurrency friendliness in the case of large or infinite iterables.  However, we have no evidence that anyone uses most with iterables in that way.  So, the simplest thing to do is simply to plow through the iterable as quickly as possible, like we do for arrays in fromArrays.
If it turns out there is a need for a concurrency-friendly version, we can entertain the idea of adding a new API or separate package for that.

Simplify fromIterable, remove tick insertion

---

.github/issue_template.md
.github/pull_request_template.md
CONTRIBUTING.md

This adds a CONTRIBUTING doc, plus issue and PR templates.  I'm very interested in feedback on whether this is enough or too much detail and/or burden.  We want guidelines that are helpful and low friction for contributors and maintainers :smile:
Close #416

Add CONTRIBUTING, issue and PR templates

---

src/Stream.js

Fix incorrect name for scheduler parameter

Fix naming

---

src/source/fromArray.js

fromArray: inline singly-invoked function.

---

docs/api.md
src/combinator/slice.js
src/index.js
test/slice-test.js

Adds `skipAfter` combinator discussed in #427

adds skipAfter combinator

---

.eslintignore
.eslintrc
package.json
test/flow/observable.js

chore(test): move flow tests

---

PACKAGES.md

List the small most packages that we published at [craft ai](http://www.craft.ai)

List craft-ai/most-utils packages

---

src/combinator/limit.js
test/limit-test.js

Fix #514 
Avoid repeating last event in the case where end is delayed beyond the debounce window of the last event.

Clear debounce timer when propagating debounced event
