- docs/api.md
- lib/source/iterate.js
- lib/source/periodic.js
- test/combinator/timestamp-test.js
- test/source/periodic-test.js
This deprecates `most.repeat` in favor of adding a value to `most.periodic`, eg `most.periodic(period, x)`.
Close #74
> Add value to most.periodic()

- docs/api.md
- lib/combinator/combine.js
- lib/combinator/transform.js
- lib/sink/IndexSink.js
- test/combine-test.js
- test/lift-test.js
This is a much more sensible behavior for applicative.  The previous cross product (which is standard for a finite, synchronous list) had the very serious issue of observing the `xs` stream many times.  The new approach applies the latest `f` to the latest `x`, when either a new `f` or new `x` arrives.  Or, put another way, it applies a *time-varying function* to a *time-varying value*, which is a fairly intuitive definition, imho.
The standard ap laws still pass, which further reinforces that this is a valid approach.
Note that this changes the behavior of combine such that it only ends once all input streams end.  That's potentially a breaking change, so will go out in 0.12.0.
Close #73
> Make applicative more sensible

- docs/api.md
- lib/source/generate.js
- lib/source/iterate.js
- lib/source/unfold.js
- most.js
- test/helper/ArrayIterable.js
- test/helper/Iteration.js
- test/helper/delayPromise.js
- test/source/generate-test.js
This computes a (potentially infinite) stream, similarly to `most.unfold` or `most.iterate`, from an *async* generator--that is, a generator that yields promises.  This allows the generator to control event times.
For example, compute an infinite stream of random values at random intervals:
```js
function* randoms() {
for(;;) yield new Promise(resolve => setTimeout(() => resolve(Math.random()), 1000 * Math.random()));
}
var stream = most.generate(randoms);
```
Still needs:
> Add most.generate to compute a stream from an async generator

- docs/api.md
- lib/source/fromEvent.js
- test/source/fromEvent-test.js
I haven't thought of a reason *not* to deprecate it.  We could release this deprecation in 0.13 and remove for either 0.14, or 1.0.  If we think of a reason to keep it between now and then, we can reinstate it.
Still needs:
See #86
> Deprecate fromEventWhere

- .jshintrc
- lib/base.js
- lib/combinator/filter.js
- lib/combinator/transform.js
- lib/fusion/Filter.js
- lib/fusion/FilterMap.js
- lib/fusion/Map.js
- lib/predicate.js
This implements the filter.filter, map.map, and filter.map fusion from #85.  I moved the Map and Filter sources to lib/fusion, since Map needs to import Filter now.  I also added FilterMap which fuses a filter and a map.  It can be further fused with subsequent map steps on the right.
I'm still not crazy about the `instanceof` checks, but they're fairly obvious, and I can't see a better way atm--definitely open to suggestions (`source.constructor === Map` ???).  The impact of the `instanceof` checks shouldn't even be noticeable since they happen at stream creation time.  The benefit of the fusion at propagation time far outweighs it.
> Implement filter + map fusion

- docs/api.md
I was unable to understand the documentation until I added this closing paren.
Thanks for your work on this library. It and the fantasy-land spec have been good footholds for understanding the underlying principles, and I'm still digging in.
> Add missing closing paren to `until` example

- lib/combinator/transduce.js
- package.json
This supports both the legacy and new protocols.  My plan is to release this as 0.13.1, and then remove support for the legacy protocol in 0.14.0 (which may actually be 1.0)
Close #114
> Update to new transducer protocol

- docs/api.md
- lib/scheduler/PropagateTask.js
- lib/source/AsyncSource.js
- lib/source/MulticastSource.js
- lib/source/create.js
- lib/source/fromEvent.js
Extract AsyncSource from MulticastSource. fromEvent now subscribes synchronously, but maintains call stack safety for EventEmitter by buffering EventEmitter events into the next tick.
Close #116
> Improve EventEmitter and EventTarget subscription.

- lib/combinator/limit.js
- test/limit-test.js
- test/timeslice-test.js
When debounce ends, if there is a pending event, it is now emitted before ending the stream.  This commit also improves the reliability of several time-based tests, including debounce tests.
> Fix debounce final event handling

- docs/api.md
- lib/combinator/filter.js
- most.js
- test/filter-test.js
- test/most-test.js
Use new name `skipRepeats` and `skipRepeatsWith`.  Deprecate `distinct` and `distinctBy`.
Close #94
> Rename distinct -> skipRepeats

- lib/combinator/concatMap.js
- lib/combinator/flatMap.js
- lib/combinator/merge.js
- lib/combinator/mergeConcurrently.js
- lib/combinator/switch.js
This reuses `until` and `concurrentMergeMap` to achieve the same behavior with much less code.
> Simplify switch() using until() and concurrentMergeMap()

- docs/api.md
- lib/combinator/lift.js
We'll need to add a section on using the curried forms of `map` and `combine` instead of `lift`.
> Deprecate lift

- lib/combinator/multicast.js
- most.js
- test/combinator/multicast-test.js
This adds stream.multicast() that converts a stream into a multicast stream (as one of the solutions to #139).
This will probably be superseded by internal changes that will handle multicasting in a more user-friendly way. Maybe it should be denoted as deprecated from the very beginning? ;)
No documentation (yet). No tests as it feels like too simple to break/test.
I've added new combinator even though it is extremely simple (could be done in most.js main file). Any hints if this is a good approach?
> Add multicast combinator

- examples/drag-n-drop/index.html
- examples/drag-n-drop/main.js
- Mouse move and up events are on the whole page, avoiding loosing the
box when moving fast.
- Memorize the mouse down location, to avoid centering box on mouse.
- Prevent default mouse down event to avoid selecting text in box in FF.
> Improve drag'n'drop example

- docs/api.md
I'm guessing you mean `just` instead of `most.just` :-)
Edit: found another copy/paste regression in `skipWhile`
> api doc fixes

- lib/combinator/accumulate.js
- test/accumulate-test.js
Scan was clobbering the stream end value by substituting the last value in the stream for the end value.  This makes scan propagate the end value.  As a bonus, it also simplifies the code slightly.
Fix #162
> Make scan preserve end value

- lib/combinator/limit.js
Previously of c36db75fb8ddca310014c7e353e3970ba5f720d8 it was also `ThrottleSink.prototype.end   = Sink.prototype.end;`. Was there a reason why this has been changed?
> remove unnecessary Function#call in ThrottleSink#end

- test/perf/concatMap.js
- test/perf/filter-map-reduce.js
- test/perf/flatMap.js
- test/perf/package.json
- test/perf/runners.js
- test/perf/scan.js
- test/perf/skipRepeats.js
- test/perf/zip.js
This updates all of the libraries to their most current versions as of (December 5 2015) and adds RxJS 5 to the tests as well.
Note that Kefir has removed their `reduce()` method and needed to be changed to `scan()`
> Update performance tests

- lib/combinator/accumulate.js
- lib/combinator/build.js
- test/combinator/sample-test.js
This also vastly speeds up startWith and concat by relying on flatMapEnd instead of concatMap.
Fix #175
> Improve scan initial value handling.

- docs/api.md
- most.js
- test/combinator/mergeConcurrently-test.js
It's used to implement join, flatMap, and concatMap, so is a generally useful building block.  I don't see any reason not to make it available.  We can bikeshed the name :)
Still needs:
> Add mergeConcurrently to public API

- docs/api.md
- most.js
- test/most-test.js
for flatMapEnd and flatMapError.
During discussion on [gitter](https://gitter.im/cujojs/most), we settled initially on `continueWith`, and `recoverWith`.  Those aren't set in stone yet, but definitely are the strongest contenders.
Feedback and other naming suggestions welcome!
> Add continueWith and recoverWith as proposed new names

- lib/combinator/promises.js
- most.js
- test/combinator/promises-test.js
This doesn't change the public API.  It only fixes the use of `await` as an identifier in lib/combinator/promises.js
Fix #184
> Fix await() name conflict w/es7 await

- docs/api.md
- most.js
- test/combine-test.js
- test/perf/README.md
- test/perf/merge.js
- test/perf/package.json
This exposes the existing array versions of merge and combine, since they can be useful at times, and `.apply(undefined, streams)` is ugly.
Docs and unit test update included.  This also adds a perf test for merge.
> Expose mergeArray and combineArray

- lib/combinator/merge.js
- test/perf/README.md
This uses a specialized merge implementation instead of `mergeConcurrently` to get almost 2x improvement, at the cost of about 50 min+gzipped *bytes*.  Seems worth it.
> Improve merge perf

- lib/disposable/dispose.js
- test/disposable/Disposable-test.js
- test/disposable/SettableDisposable-test.js
- test/disposable/dispose-test.js
Disposal was previously safe in the face of rejected promises.  That is, all other resources would be disposed even if one or more of them failed by returning a rejected promise.  Disposal was not safe in the face of exceptions.
There are 2 ways to handle thrown exceptions during disposal:
1. Declare that disposables *must not throw*, and any disposable that does is broken and should be fixed, or
2. Catch exceptions and turn them into rejected promises, and let the current machinery handle them safely.
This PR does 2.  However, I'm not convinced it's the right thing, since it allows callers to be less rigorous.  So, feedback and discussion welcome!
This also adds unit test coverage for disposables.  If we decide to go with option 1, we can remove the one `try/catch` spot in …
> Safely dispose in the face of exceptions

- lib/combinator/errors.js
- test/errors-test.js
The error architecture was slightly too aggressive, allowing `recoverWith` to recover from errors that occur later in the sink chain.  It should only recover from errors that occur earlier.  The specific change in this PR, while perhaps slightly counterintuitive at first, makes error handling more intuitive for users.
Using the words "backwards" and "forwards", and "before" and "after" is a little weird, but, imho, makes for a good mental model.
Applying combinators to a stream effectively composes a *source chain* that defines the behavior of the stream.  When an observer begins observing a stream, a "run" message is sent "backwards" through the source chain, from the observer to the ultimate producer source--the one that will produce events in the first place.  As it travels, that …
> Make error architecture less aggressive

- docs/api.md
- lib/combinator/build.js
- most.js
It doesn't seem to be useful.  If there's a need for it, it could be published as a separate package.
We can release 0.18.1 with the deprecation, and remove it in 0.19.0.
> Deprecate cycle()

- docs/recipes/unfold-promises.md
It looks like reqr.es has done away and the project is now hosted at reqres.in . I'm not sure what the api returned before - I'm assuming it is similar.
> Update reqr.es links in example.

- docs/api.md
`countdownGet` should be `countdown`
> Fix most.generate example

- lib/combinator/mergeConcurrently.js
- lib/scheduler/Scheduler.js
- lib/source/ValueSource.js
Fix for case that could cause cancelAll to remove the wrong tasks from the scheduler queue.
Couple other small improvements:
1. Use new, safer `tryDispose` in mergeConcurrently.
2. Cancel scheduled task wrapper in ValueSource, instead of only disposing the task itself.  Canceling the scheduled task wrapper removes it from the scheduler *and* disposes the underlying task.
> Fix scheduler cancelAll

- lib/combinator/promises.js
This stabilizes sample() and the interaction between `fromPromise()` with *already-fulfilled* promises and `just()`.
[Read this](https://gist.github.com/briancavalier/a27ddc247dd118ae5508) for more information.  It's not clear yet whether this is the best long term solution.  However, it seems reasonable for now, and deletes far more code than it adds.
Close #201
> Simplify fromPromise using awaitPromises+just.

- docs/api.md
This was never the intent of `most.create`, but wasn't really clear in the docs.  Now that `most-subject` exists, there's no reason even to try it.
See #204
> Clarify that pulling add/end/error out of closure is unsupported

- lib/combinator/combine.js
- lib/combinator/merge.js
- test/combinator/merge-test.js
- test/perf/merge.js
This implements fusion/flattening for adjacent/nested `merge` operations.  This means there is zero performance hit for nested merges.  For example, if a function returns a merged stream to you, and you then merge it with another stream, that structure will be flattened to a single merge.
* `a.merge(b).merge(c)` effectively becomes `merge(a, b, c)`
* `merge(a, merge(b, c))` effectively becomes `merge(a, b, c)`
It works by concatenating the sources arrays of any nested Merge sources, in effect "flattening" nested merge operations into a single merge.
I had to change `combine` so that it doesn't use mergeSources: since combine is *not* associative, it can't be flattened in the same way.
> Implement fusion/flattening for merge

- docs/api.md
The description says: `Maintain a sliding window of (up to) 3 values in an array` and not 10
> Fix most.scan example

- package.json
Got some messages while runing `npm run build` on windows
1. `Error parsing arguments for flag 'c': 'warnings=false'`  
Windows may use only double quotes in cmd, and unix can use both. So changing to double will make both happy
2. `output.file will be deprecated: Use 'output.filename' instead`  
Used webpack v1.12.14, pretty obvious message
> Fix build script warnings for windows

- docs/api.md
- lib/combinator/concatMap.js
- lib/combinator/flatMap.js
- lib/combinator/mergeConcurrently.js
- test/combinator/concatMap-test.js
:warning: Experiment :warning:
Add `mergeMapConcurrently`, which lazily maps and merges.  Convert `concatMap` to use it, which allows `concatMap` to be lazy.
While the end result is *almost* indistinguishable from eager `concatMap`, it does change when the mapping function is called, which can change the timing of I/O, etc.  See the example in #217.  It eagerly fetches all of the items in parallel with the current eager `concatMap`, but fetches them in a non-overlapping sequence when `concatMap` is lazy.
> Add mergeMapConcurrently

- lib/combinator/switch.js
- test/perf/switch.js
This PR returns to a custom impl for `switch` to increase perf substantially.  Switch is a common and useful combinator, so the extra code here seems worthwhile.
The simplified impl in master is pleasing and intuitive, but uses *two* of our biggest perf hits: `multicast`, and  `mergeConcurrently`.  Given that, it performs admirably, but this custom impl annihilates it :)
Custom impl:
```
switch 100000 x 1000 streams
-------------------------------------------------------
most               1156.98 op/s ±  0.96%   (82 samples)
```
Master:
```
switch 100000 x 1000 streams
-------------------------------------------------------
most                 56.04 op/s ±  7.22%   (65 samples)
```
Custom impl:
```
-rw-r--r--  1 brian  staff   11101 Apr 14 08:29 most.min.js.gz
```
Master:
```
-rw-r--r-- …
```
> Improve switch perf

- lib/combinator/errors.js
- lib/combinator/promises.js
- lib/sink/SafeSink.js
- test/combinator/promises-test.js
- test/errors-test.js
- test/sink/SafeSink-test.js
Avoids timing issue when recovering--see included unit test.
> Ensure previous end events cannot disable recoverWith

- lib/combinator/slice.js
- test/slice-test.js
This fuses slice.slice to slice.  Because take and skip are both implemented as slice, it also fuses skip.take and take.skip to slice. This allows *any number* of adjacent take, skip, and slice to be fused into a single slice.
> Add slice fusion

- lib/combinator/slice.js
- test/helper/stream-helper.js
- test/perf/package.json
- test/perf/slice.js
- test/slice-test.js
This simplifies slice a bit, as well as simplifying its unit tests with a new expectArray helper.
It also adds experimental map+slice commutation.  That could be moved to another PR.  It turns .map.slice into .slice.map, which is safe and enables two perf scaling benefits:
1. Slice will decrease or leave unchanged the number of items in the stream.  Typically it will decrease the number, so slice.map typically will do less work than map.slice, while yielding the same result.  At worst, it will do the same amount of work.
2. Commuting allows for more map+map fusion.  For example: map.slice.map will be commuted to slice.map.map, and then fused to slice.map.
> Simplify slice

- .markdown-doctest-setup.js
- docs/api.md
- docs/concepts.md
- docs/recipes/event-delegation.md
- package.json
Hello!
I'm the author of [markdown-doctest](https://github.com/Widdershin/markdown-doctest), a tool for automatically testing that documentation examples are runnable. The idea is that it runs as part of the CI process so that new documentation doesn't add any faults and if any breaking changes are made it's clear.
I've integrated it with most, and as part of that I fixed a few typos in the documentation. 
markdown-doctest is currently used with RxJS and xstream, among other libraries.
I've set it up here so that it runs after the test suite when you run `npm test`. It's also possible to set it up so that it only runs on CI.
Let me know what you think.
> Test documentation with markdown-doctest

- lib/combinator/accumulate.js
- lib/scheduler/Scheduler.js
As discovered in #208, the underlying use of `continueWith` (via `concat` via `startWith`) in scan was delaying observation of the input stream.  This caused a race condition with later combinators that may choose not to emit an event until all their input streams have emitted at least one event, such as `combine` and `sample`.
This changes makes scan *simultaneously* arrange to emit the initial value, and observe the input stream.  Since streams *must* use the scheduler to begin emitting events, this is safe (or, to put it another way, any stream that emits an event synchronously--and thus would win the race with the initial value--is broken and should be fixed).
Fix #208
> Make scan observe stream immediately

- lib/combinator/limit.js
- test/limit-test.js
Based on similar principles as slice fusion and map-slice commutation from #242:
1. `throttle(n).throttle(m)` can be fused to `.throttle(max(n, m))`, and
2. `.map(f).throttle(n)` can be commuted to `.throttle(n).map(f)`, since map cannot change the time or proportion of events.
Also, updated throttle test to use the `atTimes` helper, for a more reliable test.  All existing tests pass.
> Add throttle fusion and map-throttle commutation

- .markdown-doctest-setup.js
- docs/api.md
- lib/combinator/thru.js
- most.js
- package.json
- test/combinator/thru-test.js
Most's current direction is to provide non-core functional APIs via separate packages, which gets us true modularity without the problems of modifying prototypes.  This PR adds `stream.thru(f)` to allow functional APIs to be used in a fluent way.  For folks who prefer fluent APIs, this allows using those functional APIs with of mixing the two styles.
For example, fluent users have the option of using `thru`:
```js
import hold from `@most/hold`
import { click } from `@most/dom-event`
click(someElement)
.tap(ev => ev.preventDefault)
.map(ev => ev.target.value)
.thru(hold)
.observer(x => console.log(x))
```
rather than mixing functional and fluent:
```js
import hold from `@most/hold`
import { click } from `@most/dom-event`
hold(click(someElement)
.tap(ev => ev.preventDefault)
.map(ev => …
```
> Add thru(), functional-fluent adapter method

- lib/combinator/limit.js
- lib/scheduler/Scheduler.js
- lib/source/ValueSource.js
- lib/source/core.js
- lib/source/fromArray.js
- lib/source/periodic.js
- test/helper/testEnv.js
Previously, these were just using `0` as their `t` value.  It seems tough to me to rigorously (mathematically) justify any value of `t` for something like `just(1)`.  When does 1 "occur"?
**tl;dr;** See lib/source/core.js and lib/source/fromArray.js for the important changes.
So, after some discussion on gitter, it seemed like the right thing to do is to make a *practical* choice about `t`.  We bounced around several ideas:
1. Use observation time, i.e. `scheduler.now()` at the time the Stream provides the value to an observer.
- There was discussion about what the time origin of `scheduler.now()` should be.  For example, currently it is the same origin as JavaScript `Date`, the unix epoch.  Another option is *program start*: the scheduler would use `Date.now()` at VM startup time as the …
> Use observation time for just and fromArray

- lib/sink/DeferredSink.js
DeferredSink was partially broken internally, not sure how it happened ... probably just a bit of code rot.  This simplifies it slightly and cleans it up.  It probably needs a more thorough overhaul in another PR to make it more efficient, but this solves the immediate issue.
Fix #258
> Fix DeferredSink

- docs/api.md
- lib/source/create.js
- most.js
The plan is to move `most.create` to a `@most/<package>`.
It has always been a last resort for situations that force using an imperative push approach, and so is outside most.js's core mission, which focuses on providing a declarative API.  Moving it to a separate package means it will still be available for those situations, but will also help to make clear the imperative/declarative distinction.
> Deprecate create, prepare to move to separate package

- type-definitions/most.d.ts
Add subscribe()
export Stream class needed to write 3rd party libraries in TypeScript
Add Source interface
Add Sink and Scheduler, and Disposable interfaces to complete Source interface
Add Task, ScheduledTask to complete Scheduler interface
Add Subscriber and Subscrition interfaces as needed by `subscribe()`
> chore(TS): update typescript definitons

- docs/api.md
- lib/sink/DeferredSink.js
- lib/source/create.js
This adds links to [`@most/create`](https://github.com/mostjs/create), and applies recent fixes from from https://github.com/mostjs/create/pull/2, as well as other simplifications from that repo.
> Add links to mostjs/create, port fixes

- type-definitions/most.d.ts
Hello!
The small local Promise definition embedded in `most.d.ts` seems both unneeded and conflicting with two of the most widely used typescript setups:
- Compiling with ES6 as a target, in which case the typescript compiler automatically add `lib.es6.d.ts` which come with a complete Promise definition.
- Compiling with ES5 as a target and including `es6shim.d.ts` which also come with a comprehensive Promise definition. For instance, Angular 2 do it (can't believe I took them as an example! :D) and it seems to be widely advised on various stackoverflow posts by even typescript compiler contributors.
This is the setup I'm using and removing the definition fixed all errors.
The local Promise definition also has an incompatible interface. So if I use `fetch` that return a `Promise` defined …
> Remove Promise from typescript definition

- docs/api.md
- lib/observable/getObservable.js
- test/observable/getObservable-test.js
In response to [issue#283](https://github.com/cujojs/most/issues/283), this PR proposes letting any *thing* that implements the Observable interface through the `getObservable` function. Right now it appears this function is only used in the `most.from` method.
The criteria has been changed to reflect the wording in the API docs for `most.from` [here](https://github.com/cujojs/most/blob/master/docs/api.md#mostfrom):
> ... it must have a [Symbol.observable]() method that return an object with a well-behaved .subscribe() method.
*(maybe I should add a spelling correction for return?)*
The following was changed:
* check if truthy `o` has an observable Symbol function (`oSf`) on it.
* remove the unbinding and rebinding of the `oSf` (Did not see the need to do this, will totes put back if ya …
> Allow anything that implements Observable to be returned from getObservable

- docs/api.md
Remove from TOC, and refactor `zip` docs so they no longer mention `most.create`.
Close #286 
cc @nissoh
> Remove dangling references to most.create

- lib/observable/getObservable.js
- most.js
- test/combinator/continueWith-test.js
- test/most-test.js
- test/observable/getObservable-test.js
From #293:
> So when the symbol-observable package went to 1.x, it was babel-ified and as such, any common JS reference needs to pull from default name space here:
> ...
> Just needs to be:
>
> var symbolObservable = require('symbol-observable').default;
Fix #293
> Update symbol-observable 1.x usage

- .travis.yml
eslint 3 officially dropped support for node 0.12, so this PR drops node 0.12 from travis.  We *could* just decide not to lint on 0.12 and still run unit tests, but I like the simplicity of just moving on, especially since node 4 is LTS.
> Remove node 0.12 from travis

- lib/combinator/switch.js
- test/switch-test.js
This fixes a fatal typo 😖 in the `switch` source code that caused disposing to fail.  The failure manifested under specific conditions (see #300).  Added a unit test that simulates those conditions.
This also adds a sane end time value, instead of `0`, and updates switch-test to ES6 source.
Fix #300
> Fix typo in switch dispose.all setup

- README.md
Also fixed Promises/A+ logo url. It was a redirect and GitHub couldn't handle it for some reason (at least I see broken image).
> Add mention about Static Land compatibility

- type-definitions/most.d.ts
recoverWith expects a stream of chained value type. I believe this is a the proper typing
> most.d.ts recoverWith

- docs/api.md
Browsing the docs I found myself clicking that link to no avail.
It should instead take you to to the `chain` operator.
> Fixes #flatmap link leading nowhere

- type-definitions/most.d.ts
To get the proper type you have to overwrite whole expression. this fix gives the ability to manually cast type that has to satisfy  the constraint of 'Event'.
````typescript
fromEvent('mousemove', document.body) // evaluates type of Stream<Event>
fromEvent<MouseEvent>('mousemove', document.body) // evaluates type of Stream<MouseEvent>
fromEvent<CSSStyleDeclaration>('mousemove', document.body) // error [ts] Type 'CSSStyleDeclaration' does not satisfy the constraint 'Event'
````
> Type correction fromEvent most.d.ts

- .editorconfig
- src/observable/subscribe.js
- test/observable/subscribe-test.js
- test/observable/unsubscribe-test.js
by simply walk around the codebase
i think this is propbaly the fix for issue #360
by checking `disposable.disposed` before calling the `next` callback
thoughts? @briancavalier
> should noop when it's already disposed

- type-definitions/most.d.ts
The interface for `Iterable` was empty.
When writing something like `most.from([1,2,3])` the result was typed `Stream<{}>` instead of `Stream<number>`.
This pull request fixes cases like that.
Originally I only accounted for arrays with:
```
declare interface Iterable<A> { [key: number]: A; }
```
but, by definition, `Symbol.iterator` is probably more suitable for _Iterators_.
> Fix `Iterable` interface

- test/perf/README.md
- test/perf/merge.js
NOTE: I had to remove highland from the `merge` test, as it never finishes on my machine.
> Update perf results for node 6.9.2 and latest libs

- docs/api.md
Before, only the fluent-style `switch` was mentioned in the API docs.
However, because of a native language conflict, `switch` cannot be
exported as a functional API.
This commit adds point-free substitute `switchLatest` to the API docs.
Closes #374
> docs(API): add switchLatest

- test/perf/package.json
- test/perf/switch.js
Also, add switch test to the full perf test run.  ht @davidchase for [finding the mistake](https://github.com/mostjs/core/pull/2#issuecomment-269335352) that was preventing the xstream test from running.
> Fix xstream switch perf test

- type-definitions/most.d.ts
sampleWith's output type should be the same as the stream that is being consumed. The extra type parameter allowed for any type - removing the generic fixes the typings.
> Fix typing of sampleWith combinator

- docs/api.md
- type-definitions/most.d.ts
It's proven to be basically useless in practice.  Also, the ES Observable proposal, which includes the an end value, has gotten more complicated, which makes the simplicity of [Fantasy Observable](https://github.com/staltz/fantasy-observable), which doesn't have an end value, much more appealing.
> Deprecate end/complete value parameter where applicable

- docs/api.md
- src/index.js
- src/source/periodic.js
Add deprecations for all aliased functions and methods so they can be removed in 2.0.0.  Also deprecated `periodic`'s 2nd arg, since you can just use `constant`, `map`, or even `zip` to provide values.
> Deprecate aliased functions, update docs

- src/source/fromIterable.js
Using Webpack 2 to compile an application using `most`, the minification step generates this error:
```bash
ERROR in my_app.js from UglifyJs
SyntaxError: Unexpected token: name (r) [./~/most/src/source/fromIterable.js:22,0][my_app.js:6294,6]
```
```javascript
function runProducer (t, iterator, sink) {
let r = iterator.next()
^
// ...
}
```
The generated bundle would also fail in browsers that don't support ES6 because of the `let` keyword.
Webpack 2 uses the value of the `module` key in `package.json` to resolve the `most` package with ES2015 modules, so it can apply tree shaking. In `most`, this is just the plain source code in `most/src`.
In the package `module` points to, [all other statements than `import` and `export` should be usable in the environments `most` wants to …
> ES5 compatibility in ES2015 module build

- type-definitions/most.d.ts
Fix `from` TS type definition to allow accepting the full compliment of types it can coerce.
Fix #405
> fix(type-definitions): Expand types accepted by from() to match reality

- src/observable/fromObservable.js
- test/observable/fromObservable-test.js
Currently there is no error handling around `fromObservable` and can cause errors to be thrown in place rather than through most's sinks to be handled via `recoverWith` etc.
Fixes #407
> fix(fromObservable): allow proper error handling

- type-definitions/most.d.ts
The constraint `T extends Event` doesn't account for node.js EventEmitter's which are clearly [accounted for in the implementation](https://github.com/cujojs/most/blob/7d27cd50afa2cacb6ee39fc62b424c73d61fe9e5/src/source/fromEvent.js#L27-L28).
I've added it as an overload to further clarify that in those situations the `useCapture` parameter is not used.
> Remove `extends Event` constraint for `fromEvent`

- src/Stream.js
- test/Stream-test.js
- type-definitions/most.d.ts
Add delegating run() prototype method in preparation for compatibility with upcoming @most/core changes.  It simply delegates to the stream's source.
> feat(Stream): add delegating run method

- docs/api.md
See discussion in #415.  We'd prefer to keep thru as a single arg, and encourage folks to allow multiple args via partial application of the transform.
Close #415
> Add notes about partial application with thru()

- docs/api.md
In `api.md` where backtick code block is involved inside header, space is missing. Such headers was broken. The PR fixes this.
> api.md: fix space after h4 header and before code block.

- src/combinator/slice.js
Prevent `take` and `takeWhile` from disposing twice when they end the stream early.
SliceSink was explicitly calling dispose and `sink.end`.  However, `sink.end` also always [leads to dispose in runSource](https://github.com/cujojs/most/blob/master/src/runSource.js#L39).  Hence, dispose was being called twice.  This was partially hidden by the fact that SliceSink used `dispose.once` to "memoize" the effect of the disposable it was holding.
This fix has the added benefit of allowing SliceSink and TakeWhileSink to follow the more standard "just wrap the incoming sink" pattern, rather than having the additional responsibility to activate the source and manage the returned Disposable.
Fix #426
> fix(take): Fix take double dispose

- type-definitions/most.d.ts
Adds type definitions for `skipAfter`
> add skipAfter to type-definitions

- README.md
Fix simple typo caused when https://github.com/DefinitelyTyped/DefinitelyTyped moved all the types under /types
> chore(readme): fix broken link to es6-shim.d.ts

- src/observable/subscribe.js
- test/observable/subscribe-test.js
Use object wrapping rather than the typeof check to determine if subscriber is valid. Correctly handles objects and functions and is compatible with how RxJS and zen-observable behave as they don’t distinguish between objects and functions. (issue #445)
> Improve the checking of subscriber objects to match RxJS and zen-observable (#445)

- docs/api.md
- package.json
Update markdown examples to use `@most/hold` 2.x
> chore(deps): Update examples to use @most/hold 2.x

- type-definitions/most.d.ts
The type definition `Scheduler.delay(task)` was incorrect. I updated it to `Scheduler.delay(delay, task)`.
> fix(type-definitions): Scheduler method signatures

- docs/api.md
I never remember if most tries to be smart and `delayTime` is in seconds, or if it's ms ...
This adds the unit on the delayTime argument of the delay operator in the api docs.
> docs(api): specify unit of delay

- type-definitions/most.d.ts
The filter from rxjs uses typeguards in order to infer the new type of a stream after a filter operation. This isn't in most, so I implemented it.
Example by what I mean:
```js
filter(isString, from([1, 2, 'hello']))
.map(v => {}) // v at this point is inferred to be a string rather than string | number
```
I tried it out on my machine as a method of a stream and as a function. It works on both.
I don't think unit tests or documentation are necessary for this change, it falls back to the old typing if no type guard is found.
> Improve filter type definition

- src/combinator/slice.js
Fix #466
Reinstate immediate synchronous dispose in `take` and `takeWhile` rather than relying solely on end() to dispose the whole Sink chain.  Use SettableDisposable to deal with cases where source stream may end synchronously before `source.run` returns (and thus `SliceSink`'s `this.disposable` is not yet assigned)
> fix(slice): Use SettableDisposable and synchronous immediate dispose

- docs/api.md
- src/combinator/thru.js
- test/combinator/thru-test.js
- type-definitions/most.d.ts
See https://github.com/cujojs/most/issues/471
Make `thru` parametric in its return type to admit functions that return something other than a Stream.
> feat(thru): Make thru parametric in its return type

- src/combinator/limit.js
- test/limit-test.js
When disposing a debounce stream we also need to dispose the source disposable
I was trying to use `debounce` in the following scenario
```
combine(...streams$)
.debounce(1000)
.chain(chainStream)
.subscribe(observer);
```
But I soon realized that when I tried to dispose the above stream, it would ignore disposing the stream (source stream) that comes before the debounce.
> Dispose the source disposable

- type-definitions/most.d.ts
Fix #457 
Constrain `await`'s `this` type, add missing `awaitPromises` alias.
> fix(type-definitions): Constrain this type, add awaitPromises alias

- README.md
Most itself support and fantasy and static land. Also monad already includes functor and applicative interfaces according both spec
> Clean up readme types

- src/observable/subscribe.js
- test/observable/subscribe-test.js
This example swallows errors
```js
const stream = most.throwError(1);
stream.subscribe({
next: v => console.log(v)
});
```
> Throw error if handler is not present

- type-definitions/most.d.ts
Use TS `this` argument type to provide correct types for higher-order _methods_ join, switch, etc. in the same way that awaitPromises does.
> fix(types): improve higher-order combinator TS types

- .flowconfig
- package.json
- src/index.js.flow
- type-definitions/most-flow-test.js
According [spec](https://github.com/tc39/proposal-observable#observer) all props of subscriber can be omitted. Also I added first test case for subscriber and would like to improve coverage step by step.
> Allow omitting properties of subscriber

- package.json
flow-bin should be a devDep but is currently a dep.  This PR moves it to a devDep, and updates flow to the latest version.
Close #486
> fix(deps): Move flow-bin to devDeps

- src/combinator/delay.js
- test/delay-test.js
- test/helper/testEnv.js
Fix bug in delay that caused pending delayed events to be propagated after dispose.
Fix #488
- So far it's has proven difficult to write a *simple* unit test for this.  I may opt for a more complex test to get this merged.
> fix(delay): Fix delay dispose

- src/index.js.flow
These methods depends on `this` indentifier which is forbidden in flow 0.55. Same as `join`
> Remove await and awaitPromises methods

- docs/api.md
Removed a dangling anchor tag that was breaking the header for ES Observable interop
Should be good to go!
> removed header-breaking anchor tag

- docs/api.md
Close #524 
Document the behavior when awaitPromises encounters a forever pending promise. This behavior is implied in the existing documentation, in that event order is preserved. However, it may not be obvious to some that preserving order implies that a forever-pending promise will prevent all subsequent events. This PR adds an explicit section that hopefully will help to make it clear.
Equivalent change for `@most/core`: https://github.com/mostjs/core/pull/256
> Add note about forever pending promises

- README.md
- docs/api.md
`@most/core` is the future of mostjs, and most 2.0 is close.  Most 2.0 will be based on `@most/core`, will be directly compatible with it, and will be a trivial upgrade for folks who prefer a single dependency in their package.json.
The goal of this addition is to help devs make a more forward-compatible choice for new projects and let them know there will be a guide to help them upgrade existing projects.  It encourages devs to pick `@most/core` now for new projects, and points existing most 1.x-based projects to the upgrade guide (still a WIP as of this writing).
> Add note to point devs at @most/core for new projects

- .travis.yml
They were behind and manually updating is annoying.  Switch to latest + lts as per [Travis docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions).
> Update Travis node versions

- src/index.js.flow
- type-definitions/most.d.ts
Hi folks,
Currently the TS definitions of `recoverWith` expect the recovered stream to be of the same type of the one that errors. This feels off, since we'll often see patterns when recovering from error could for instance mean that we want a type signalling the error. This is especially true if you use a union of returned value, mapping to one of the values will prevent you to recover with another one.
For instance in my case, using `redux-most`:
```js
type Action =
| FetchSuccess
| FetchFailure
const stream: Stream<Action> =
most
.fromPromise(fetchData())
.map(response =>fetchSuccess(response.data))
.recoverWith((error: Error) => most.of(fetchError(error)))
)
```
This will error, stating that `Stream<FetchFailure>` (returned by `fetchError`) is incompatible with `Stream<FetchSucess>` …
> Authorise different returned type for recoverWith

- dist/most.js
- src/combinator/limit.js
- src/index.js
There is a small typo in dist/most.js, src/combinator/limit.js, src/index.js.
Should read `occurring` rather than `occuring`.
> docs: Fix simple typo, occuring -> occurring

- src/combinator/promises.js
- test/combinator/promises-test.js
Fix #534 
Explicitly prevent event propagation after dispose.
> Explicitly prevent propagation after awaitPromises dispose

- package-lock.json
- package.json
- src/index.js
- src/observable/getObservable.js
- test/most-test.js
This change upgrades `symbol-observable` and changes use to `symbol-observable/ponyfill` so that MostJS can be used in JS environments where the primordials are frozen to mitigate prototype pollution attacks.
I have not added unit tests to verify this, but with your consent, I can add a development dependency on SES and use that to lock down the primordials during tests.
This is not a user-visible change, but does enable MostJS to be used in more environments. I do not see a change log to mention this in.
> Use Symbol.observable “ponyfill”

- src/index.js
- src/observable/getObservable.js
- test/most-test.js
Fix build by using require for new cjs deps after https://github.com/cujojs/most/pull/541
It's a bummer, but our antiquated build setup is failing because it can't handle some kinds of CommonJS / ES module interop.  This is the simplest short term fix I could get working.  Here's what `npm run build` says:
After this change:
> Fix build by using require for new cjs deps
